# Generated by Django 4.1.2 on 2022-10-09 12:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_code', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lab_Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_no', models.FloatField()),
                ('objectives', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ilo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('discussion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('resources', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('procedure', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('results', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('supplementary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('observation', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('conclusion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Courseinformation', to='home.courses')),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LabManual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LabInformation', to='home.lab_manual')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SharedTo', to='home.user_info')),
            ],
        ),
        migrations.AddField(
            model_name='lab_manual',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LabInstructor', to='home.user_info'),
        ),
        migrations.AddField(
            model_name='courses',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CourseInstructor', to='home.user_info'),
        ),
    ]
