# Generated by Django 4.1.2 on 2022-10-11 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_user_info_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_manual',
            name='lab_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
